// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIJGsH1DQvkp2ZFhErNFXNBNamCw8W2XA',
    appId: '1:524661298876:web:0e4ad087dd309c00ca62b9',
    messagingSenderId: '524661298876',
    projectId: 'erasmusapp-dcd29',
    authDomain: 'erasmusapp-dcd29.firebaseapp.com',
    storageBucket: 'erasmusapp-dcd29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSycfOjkx_Wj5KHINvOO3ULGQh1DmVFew',
    appId: '1:524661298876:android:480a594ad9d995d7ca62b9',
    messagingSenderId: '524661298876',
    projectId: 'erasmusapp-dcd29',
    storageBucket: 'erasmusapp-dcd29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQfoFQ-iE4I7HV6CP-_zF76cYLzK9LDGI',
    appId: '1:524661298876:ios:7808c8b818099b27ca62b9',
    messagingSenderId: '524661298876',
    projectId: 'erasmusapp-dcd29',
    storageBucket: 'erasmusapp-dcd29.appspot.com',
    iosBundleId: 'com.malinowski.managmentSystemProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQfoFQ-iE4I7HV6CP-_zF76cYLzK9LDGI',
    appId: '1:524661298876:ios:e45145fa7a4000f2ca62b9',
    messagingSenderId: '524661298876',
    projectId: 'erasmusapp-dcd29',
    storageBucket: 'erasmusapp-dcd29.appspot.com',
    iosBundleId: 'com.malinowski.managmentSystemProject.RunnerTests',
  );
}
